lib: [
  "_build/install/default/lib/stylesheet_ml/META" {"META"}
  "_build/install/default/lib/stylesheet_ml/opam" {"opam"}
  "_build/install/default/lib/stylesheet_ml/stylesheet_ml.cmi" {"stylesheet_ml.cmi"}
  "_build/install/default/lib/stylesheet_ml/stylesheet_ml.cmx" {"stylesheet_ml.cmx"}
  "_build/install/default/lib/stylesheet_ml/stylesheet_ml.cmt" {"stylesheet_ml.cmt"}
  "_build/install/default/lib/stylesheet_ml/stylesheet_ml.ml" {"stylesheet_ml.ml"}
  "_build/install/default/lib/stylesheet_ml/stylesheet_ml.cma" {"stylesheet_ml.cma"}
  "_build/install/default/lib/stylesheet_ml/stylesheet_ml.cmxa" {"stylesheet_ml.cmxa"}
  "_build/install/default/lib/stylesheet_ml/stylesheet_ml.a" {"stylesheet_ml.a"}
  "_build/install/default/lib/stylesheet_ml/stylesheet_ml.cmxs" {"stylesheet_ml.cmxs"}
  "_build/install/default/lib/stylesheet_ml/stylesheet_ml.dune" {"stylesheet_ml.dune"}
]
